app-index:
   path: /
   controller: App\Controller\AppController::index

security-login:
  path: /login
  controller: App\Controller\SecurityController::login
  
users-index:
  path: /users
  controller: App\Controller\UserController::index

security-logout:
  path: /logout